/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ehu.isad;

import ehu.isad.Controllers.UI.PmaKud;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

public class App extends Application {

    private Stage stage;
    private Parent pmaUI;
    private PmaKud pmaKud;
    private Scene scenePma;

    @Override
    public void start(Stage primaryStage) throws Exception {
        stage = primaryStage;
        pantailaKargatu();

        stage.setTitle("Azterketa");
        stage.setScene(scenePma);
        stage.show();
    }

    private void pantailaKargatu() throws IOException {

        FXMLLoader loaderPma = new FXMLLoader(getClass().getResource("/pma.fxml"));
        pmaUI = (Parent) loaderPma.load();
        this.scenePma=new Scene(pmaUI);
        pmaKud = loaderPma.getController();
        pmaKud.setPmaApp(this);
    }

    public static void main(String[] args) {
        launch(args);
    }


}